# Generated by Django 6.0.1 on 2026-01-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "factory_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Fabricação"
                    ),
                ),
                (
                    "model_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Modelo"
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Placa"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="cars/", verbose_name="Foto"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_brand",
                        to="cars.brand",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carro",
                "verbose_name_plural": "Carros",
                "ordering": ["model"],
            },
        ),
    ]
