# Generated by Django 6.0.1 on 2026-01-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cars_count",
                    models.IntegerField(verbose_name="Quantidade de Carros"),
                ),
                (
                    "cars_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Valor Total dos Carros",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Inventário de Carros",
                "verbose_name_plural": "Inventários de Carros",
                "ordering": ["-created_at"],
            },
        ),
    ]
