# Generated by Django 6.0.1 on 2026-01-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
